import Steps from "@/components/steps";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OnboardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <div className="flex flex-col gap-4 md:grow">
      <Steps />
      <div className="flex flex-col grow">{children}</div>
    </div>
  );
}
